FROM openjdk:8-alpine

MAINTAINER Riccardo Balbo <riccardo0blb@gmail.com>

ENV OPENFIRE="http://www.igniterealtime.org/builds/openfire/openfire_4_3_2.tar.gz"
ARG OPENFIRE_HASH="fc7d8dbd8f3771f6f440f456dc9efc1cb50d0018044eb9bdb64472694352f4dc"

USER root

RUN  addgroup -g 1000 -S java && adduser -u 1000 -S -D -G java java
  

RUN cd tmp \
&&apk add --no-cache openssl  \
&&wget ${OPENFIRE} -O openfire.tar.gz \
&& hash="`sha256sum openfire.tar.gz| cut -d ' ' -f 1`" \
&& if [ "$hash" != "${OPENFIRE_HASH}" ]; then  echo "${OPENFIRE} hash does not match. ${OPENFIRE_HASH} != $hash"; exit 1 ; fi \
&&mkdir  openfire_ex \
&&tar -xzf openfire.tar.gz -C openfire_ex \
&&mkdir -p /opt/openfire \
&&cd openfire_ex/openfire*/  \
&&cp -Rp  . /opt/openfire/ \
&&cd /tmp \
&&rm -Rf openfire* \
&&chown -R java:java /opt/openfire \
&&mkdir -p /opt/openfire/logs/ \
&& rm -f /opt/openfire/logs/info.log \
&& ln -sf /dev/stdout  /opt/openfire/logs/info.log \
&& rm -f  /opt/openfire/logs/debug.log \
&& ln -sf /dev/stdout  /opt/openfire/logs/debug.log \
&& rm  -f /opt/openfire/logs/error.log \
&& ln -sf /dev/stderr /opt/openfire/logs/error.log  \ 
&& echo "#/bin/sh" > /opt/openfire/run.sh  \
&& echo "/opt/openfire/bin/openfire run" >> /opt/openfire/run.sh && \
chmod +x /opt/openfire/run.sh 

EXPOSE 5222 7070 7443 5269 5275 5276 5262 5263 9091 7777 5229 10000-20000 	

USER java
CMD "/opt/openfire/run.sh"

